# -*- coding: utf-8 -*-
"""zomato data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0rG0J6U-2oXHLOUmAD7oa2GcKK5Q7Kg
"""

import pandas as pd

# loading the dataset
df = pd.read_csv('/content/Zomato  raw data.csv')
df

df.isnull().sum()

df.info()

df.head(2)

"""there are no null values in the data

here the online_order and rate is stored in object type we need to convert to numeric
"""



df.dtypes

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

import numpy as np
# cleaning rate column
df['rate'] = df['rate'].str.replace('/5', '', regex=False)
df['rate'] = df['rate'].replace(['NEW', '-'], np.nan)
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

df.info()

df.head()

"""Convertiing the online_order and book_table into the boolean format"""

df['online_order'].value_counts()
df['book_table'].value_counts()

df['online_order'] = df['online_order'].str.strip().str.title()
df['book_table'] = df['book_table'].str.strip().str.title()

df['online_order'] = df['online_order'].map({'Yes': True, 'No': False})
df['book_table'] = df['book_table'].map({'Yes': True, 'No': False})

df.head(3)

df['approx_cost(for two people)'].value_counts()

df.info()

df['rate'].fillna(df['rate'].median(), inplace  = True)
df['approx_cost(for two people)'].fillna(df['approx_cost(for two people)'].median(), inplace = True)

"""Feature Engineering"""

df['cost_category'] = pd.qcut(df['approx_cost(for two people)'], q=3, labels = ['Low', 'Medium', 'High'])
df



df.to_csv('cleaned zomato data set', index = False)

print('cleaned zomato data set')

